from covid import Covid
from Fonctionnalites.speak import speak
from Fonctionnalites.translate import translate

def covcases(question):
    covid = Covid()
    country = getCountry(question)
    countryConvert = getCountryConvert(str.capitalize(country))[str.capitalize(country)]

    result = covid.get_status_by_country_name(countryConvert)
    speak(f'Il y a {result["confirmed"]} cas, et {result["deaths"]} morts dû au covide en {country}')


def getCountry(question):
    split = question.split("en ")
    country = split[1].split(" ")[0]

    # for i in range(len(split)):
    #     if split[0][0] == split[0][0].upper():
    #         country += split[i]
    #         print(country)
            # try:
            #     next = split[i + 1]
            #     if next[0][0] == next[0][0].upper():
            #         country += "+"
            #     else:
            #         break
            # except IndexError:
            #     break
    return country

def getCountryConvert(country):
    countries = {
        "états-unis": "US",
        "Inde": "India",
        "Brésil": "Brazil",
        "Angleterre": "United Kingdom",
        "Russie": "Russia",
        "France": "France",
        "Espagne": "Spain",
        "Italie": "Italy",
        "Turquie": "Turkey",
        "Allemagne": "Germany",
        "Colombie": "Colombia",
        "Argentine": "Argentina",
        "Mexique": "Mexico",
        "Pologne": "Poland",
        "Iran": "Iran",
        "Afrique du sud": "South Africa",
        "Ukraine": "Ukraine",
        "Pérou": "Peru",
        "Indonésie": "Indonesia",
        "Tchéquie": "Czechia",
        "Pays-Bas": "Netherlands",
        "Canada": "Canada",
        "Portugal": "Portugal",
        "Chili": "Chile",
        "Roumanie": "Romania",
        "Belgique": "Belgium",
        "Israel": "Israel",
        "Irak": "Iraq",
        "Suède": "Sweden",
        "Pakistan": "Pakistan",
        "Philippines": "Philippines",
        "Suisse": "Switzerland",
        "Bangladesh": "Bangladesh",
        "Maroc": "Morocco",
        "Australie": "Austria",
        "Serbie": "Serbia",
        "Japon": "Japan",
        "Hongrie": "Hungary",
        "Arabie Saoudite": "Saudi Arabia",
        "Émirats arabes unis": "United Arab Emirates",
        "Jordanie": "Jordan",
        "Liban": "Lebanon",
        "Panama": "Panama",
        "Slovaquie": "Slovakia",
        "Népal": "Nepal",
        "Birélorussie": "Belarus",
        "Équateur": "Ecuador",
        "Malaisie": "Malaysia",
        "Géorgie": "Georgia",
        "Kazakhstan": "Kazakhstan",
        "Croatie": "Croatia",
        "Bolivie": "Bolivia",
        "Azerbaijan": "Azerbaijan",
        "République dominicaine": "Dominican Republic",
        "Bulgarie": "Bulgaria",
        "Tunisie": "Tunisia",
        "Irlande": "Ireland",
        "Danemark": "Denmark",
        "Costa Rica": "Costa Rica",
        "Lituanie": "Lithuania",
        "Slovénie": "Slovenia",
        "Koweït": "Kuwait",
        "Égypte": "Egypt",
        "Grèce": "Greece",
        "Moldavie": "Moldova",
        "Arménie": "Armenia",
        "Territoires palestiniens occupés": "West Bank and Gaza",
        "Guatemala": "Guatemala",
        "Honduras": "Honduras",
        "Qatar": "Qatar",
        "Éthiopie": "Ethiopia",
        "Nigeria": "Nigeria",
        "Paraguay": "Paraguay",
        "Birmanie": "Burma",
        "Oman": "Oman",
        "Venezuela": "Venezuela",
        "Libye": "Libya",
        "Bosnie-Herzégovine": "Bosnia and Herzegovina",
        "Bahreïn": "Bahrain",
        "Algérie": "Algeria",
        "Kenya": "Kenya",
        "Chine": "China",
        "Macédoine du Nord": "North Macedonia",
        "Albanie": "Albania",
        "Kirghizistan": "Kyrgyzstan",
        "Corée du Sud": "Korea, South",
        "Ouzbékistan": "Uzbekistan",
        "Lettonie": "Latvia",
        "Ghana": "Ghana",
        "Sri Lanka": "Sri Lanka",
        "Zambie": "Zambia",
        "Monténégro": "Montenegro",
        "Norvège": "Norway",
        "Kosovo": "Kosovo",
        "Singapour": "Singapore",
        "El Salvador": "El Salvador",
        "Afghanistan": "Afghanistan",
        "Estonie": "Estonia",
        "Luxembourg": "Luxembourg",
        "Finlande": "Finland",
        "Mozambique": "Mozambique",
        "Uruguay": "Uruguay",
        "Ouganda": "Uganda",
        "Cuba": "Cuba",
        "Namibie": "Namibia",
        "Zimbabwe": "Zimbabwe",
        "Chypre": "Cyprus",
        "Cameroun": "Cameroon",
        "Sénégal": "Senegal",
        "Cote d'Ivoire": "Cote d'Ivoire",
        "Soudan": "Sudan",
        "Malawi": "Malawi",
        "Australie": "Australia",
        "Botswana": "Botswana",
        "Thaïlande": "Thailand",
        "Congo": "Congo (Kinshasa)",
        "Angola": "Angola",
        "Malte": "Malta",
        "Madagascar": "Madagascar",
        "Jamaïque": "Jamaica",
        "Maldives": "Maldives",
        "Rwanda": "Rwanda",
        "Mauritanie": "Mauritania",
        "Eswatini": "Eswatini",
        "Guinée": "Guinea",
        "Syrie": "Syria",
        "Cap-Vert": "Cabo Verde",
        "Tadjikistan": "Tajikistan",
        "Gabon": "Gabon",
        "Belize": "Belize",
        "Haïti": "Haiti",
        "Burkina Faso": "Burkina Faso",
        "Andorre": "Andorra",
        "Lesotho": "Lesotho",
        "Suriname": "Suriname",
        "Bahamas": "Bahamas",
        "Guyane": "Guyana",
        "Mali": "Mali",
        "Trinité-et-Tobago": "Trinidad and Tobago",
        "Nicaragua": "Nicaragua",
        "Islande": "Iceland",
        "Djibouti": "Djibouti",
        "Togo": "Togo",
        "Guinée équatoriale": "Equatorial Guinea",
        "Soudan du Sud": "South Sudan",
        "Somalie": "Somalia",
        "République centrafricaine": "Central African Republic",
        "Niger": "Niger",
        "Bénin": "Benin",
        "Gambie": "Gambia",
        "Sierra Leone": "Sierra Leone",
        "Tchad": "Chad",
        "Comores": "Comoros",
        "Saint-Marin": "San Marino",
        "Guinée-Bissau": "Guinea-Bissau",
        "Liechtenstein": "Liechtenstein",
        "Sainte-Lucie": "Saint Lucia",
        "Érythrée": "Eritrea",
        "Mongolie": "Mongolia",
        "Nouvelle-Zélande": "New Zealand",
        "Vietnam": "Vietnam",
        "Yémen": "Yemen",
        "Barbade": "Barbados",
        "Libéria": "Liberia",
        "Seychelles": "Seychelles",
        "Burundi": "Burundi",
        "Sao Tomé-et-Principe": "Sao Tome and Principe",
        "Saint-Vincent et les Grenadines": "Saint Vincent and the Grenadines",
        "Taïwan": "Taiwan*",
        "Papouasie-Nouvelle-Guinée": "Papua New Guinea",
        "Bhoutan": "Bhutan",
        "Diamond Princess": "Diamond Princess",
        "Ile Maurice": "Mauritius",
        "Tanzanie": "Tanzania",
        "Cambodge": "Cambodia",
        "Antigua-et-Barbuda": "Antigua and Barbuda",
        "Brunéi": "Brunei",
        "Grenade": "Grenada",
        "Dominique": "Dominica",
        "Timor-Leste": "Timor-Leste",
        "Fiji": "Fiji",
        "Laos": "Laos",
        "Saint-Kitts-et-Nevis": "Saint Kitts and Nevis",
        "Vatican": "Holy See",
        "Îles Salomon": "Solomon Islands",
        "MS Zaandam": "MS Zaandam",
        "Îles Marshall": "Marshall Islands",
        "Samoa": "Samoa",
        "Micronésie": "Micronesia",
        "Vanuatu": "Vanuatu",
    }

    return countries
